title: Blog
author: GitHub User
email: saharshtapi@gmail.com
description: Saharsh Agrawal
# > this means to ignore newlines until "show_exerpts:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
show_excerpts: false # set to true to show excerpts on the homepage
liquid-md5: /assets/icon.jpg
paginate: 7
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: saharshtapi

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/saharshtapi
      icon: x-twitter
      color: cyan
    - url: https://www.linkedin.com/in/saharsh-agrawal-146b991b4/
      icon: linkedin-in
      color: blue
    - url: https://github.com/saharshtapi
      icon: github-square
      color: purple

collections:
  Projects:
    output: true
    permalink: :permalink

# show_author: true

#animation_speed: 50

# Build settings
theme: jekyll-dash

plugins:
 - liquid-md5
 - jekyll/tagging

